version: '3.8'

services:
  app:
    build: .
    container_name: socrat_app
    ports:
      - "8020:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy   # <-- NEW
      redis:
        condition: service_started
    networks:
      - socrat_net

  db:
    image: postgres:16-alpine
    container_name: socrat_db
    environment:
      POSTGRES_USER: socrat_user
      POSTGRES_PASSWORD: socrat_pass
      POSTGRES_DB: socrat_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U socrat_user -d socrat_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - socrat_net

  redis:
    image: redis:7-alpine
    container_name: socrat_redis
    ports:
      - "6377:6379"
    networks:
      - socrat_net

volumes:
  postgres_data:

networks:
  socrat_net:
    driver: bridge